# Generated by Django 4.2.8 on 2023-12-23 16:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_model_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('bike_model', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bike_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('image_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BikeMeta',
            fields=[
                ('bikemeta_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('asking_price', models.CharField(blank=True, max_length=10, null=True)),
                ('year_of_model', models.CharField(blank=True, max_length=10, null=True)),
                ('engine_cc', models.CharField(blank=True, max_length=10, null=True)),
                ('kms_run', models.CharField(blank=True, max_length=50, null=True)),
                ('no_of_owners', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('buy_year', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.TextField()),
                ('latest_upload', models.DateTimeField(default=datetime.datetime(2023, 12, 23, 21, 55, 55, 945650))),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_meta', to='admins.bike')),
            ],
        ),
        migrations.CreateModel(
            name='BikeImages',
            fields=[
                ('bikeimage_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('image_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_image', to='admins.bike')),
            ],
        ),
    ]
