# Generated by Django 4.2.8 on 2023-12-23 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemeta',
            name='latest_upload',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 21, 56, 40, 62050)),
        ),
    ]
