# Generated by Django 4.2.8 on 2023-12-23 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_bikemeta_latest_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemeta',
            name='latest_upload',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 21, 57, 14, 22332)),
        ),
    ]
