# Generated by Django 4.2.8 on 2023-12-24 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_bikemeta_latest_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemeta',
            name='engine_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bikemeta',
            name='latest_upload',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 11, 31, 32, 791975)),
        ),
    ]
