# Generated by Django 4.2.8 on 2023-12-24 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_bikemeta_engine_type_alter_bikemeta_latest_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bikeimages',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bikemeta',
            name='latest_upload',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 13, 16, 13, 269924)),
        ),
    ]
