# Generated by Django 4.2.8 on 2024-01-06 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_bikemeta_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image_path',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='bikeimages',
            name='image_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='bikeimages',
            name='image_path',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='bikemeta',
            name='details',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='bikemeta',
            name='latest_upload',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 11, 9, 11, 149852)),
        ),
    ]
