# Generated by Django 4.1.7 on 2024-01-10 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_alter_bikemeta_latest_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemeta',
            name='latest_upload',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 21, 22, 24, 539701)),
        ),
    ]
