# Generated by Django 4.1.7 on 2024-01-10 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_alter_bikemeta_latest_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemeta',
            name='latest_upload',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 21, 42, 40, 754344)),
        ),
    ]
