# Generated by Django 4.1.7 on 2024-07-21 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_alter_bikemeta_latest_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemeta',
            name='latest_upload',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 20, 43, 5, 862549)),
        ),
    ]
